name: Check for infrastructure drift
on:
  push:
    branches:
      - master
      - develop

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of example terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v2
